name: continuous integration workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0

      - run: npm ci
      
      - name: verify lint
        run: npm run lint

      - name: run unit tests
        run: npm run test:unit

      - name: running e2e tests
        run: npm run test:e2e