@baseurl = http://localhost:3000
@token-jwt = paste-a-valid-access-token-here
@api-token = Jesus_is_my_savior

### Health check
# @name HealthCheckAction
GET {{baseurl}}

### Create a new user
# @name CreateUserAction
POST {{baseurl}}/users
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}

{
  "name": "John Doe2 - teste",
  "email": "johndoe2@email.com",
  "password": "Strong1Pass"
}

### List all users
# @name FindAllUsersAction
GET {{baseurl}}/users
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}

### Find user by ID
# @name FindUserByIdAction
GET {{baseurl}}/users/{{CreateUserAction.response.body.id}}
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}

### Find user by email
# @name FindUserByEmailAction
GET {{baseurl}}/users/search?email={{CreateUserAction.response.body.email}}
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}

### Update created user
# @name UpdateUserAction
PUT {{baseurl}}/users/{{CreateUserAction.response.body.id}}
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}

{
  "name": "John Doe Updated",
  "email": "johndoe@email.com"
}

### Delete created user
# @name DeleteUserAction
DELETE {{baseurl}}/users/{{CreateUserAction.response.body.id}}
Content-Type: application/json
x-api-token: {{api-token}}
Authorization: Bearer {{token-jwt}}
