@baseurl = http://localhost:3000
@api-token = Jesus_is_my_savior
@refresh-token = paste-a-valid-refresh-token-here

### Login with valid credentials
# @name LoginAction
POST {{baseurl}}/auth/login
Content-Type: application/json
x-api-token: {{api-token}}

{
  "email": "gabrielGodoi@email.com",
  "password": "Gabriel1"
}

### Refresh token route
# @name RefreshTokenAction
POST {{baseurl}}/auth/refresh-token
Content-Type: application/json
x-api-token: {{api-token}}

{
  "refreshToken": "{{refresh-token}}"
}

### Logout
# @name LogoutAction
POST {{baseurl}}/auth/logout
Content-Type: application/json
x-api-token: {{api-token}}
